apiVersion: v1
kind: ServiceAccount
metadata:
  name: pan-agent-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pan-agent-operator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pan-agent-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pan-agent-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pan-agent-operator
  apiGroup: rbac.authorization.k8s.io
